### ISSUE TITLE
Wrong reference to Dockerfile

### ISSUE THREAD

**Issue by gungoren** [huseyinbabal/saas-billing#1]
**Billing** pipeline builds Dockerfile in `payment` directory.

https://github.com/huseyinbabal/saas-billing/blob/966300e0f83abed4b863de689b6688a2c2902f62/.github/workflows/billing.yaml#L47

**Comment by huseyinbabal** [comment]
Fixed in [this commit](https://github.com/huseyinbabal/saas-billing/commit/ddce2756a69514ea97e9c06a41ed1ab783399e7e), thanks 🙏
